# Generated by Django 4.2.2 on 2023-06-21 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_selection"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ad",
            old_name="owner",
            new_name="author",
        ),
        migrations.RemoveField(
            model_name="selection",
            name="owner",
        ),
    ]
