# Generated by Django 4.2.2 on 2023-06-21 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0004_selection_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="selection",
            old_name="author",
            new_name="owner",
        ),
    ]
