# Generated by Django 4.2.2 on 2023-06-25 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ads", "0006_category_slug_alter_ad_description_alter_ad_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="selection",
            name="owner",
        ),
        migrations.AddField(
            model_name="selection",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
