# Generated by Django 4.2.2 on 2023-06-25 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0008_rename_author_selection_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="selection",
            old_name="owner",
            new_name="author",
        ),
    ]
