# Generated by Django 4.2.2 on 2023-06-25 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0010_rename_author_ad_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ad",
            old_name="owner",
            new_name="author",
        ),
    ]
