# Generated by Django 4.2.2 on 2023-06-26 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0011_rename_owner_ad_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="selection",
            old_name="author",
            new_name="owner",
        ),
    ]
